/**
 * Signal Dispatch — Tailwind CSS Preset
 * Generated by brand-forge v2.0.0-candidate
 * DO NOT EDIT — regenerate with: brand-forge export tailwind
 */

/** @type {import("tailwindcss").Config} */
export default {
  theme: {
    extend: {
      colors: {
        primary: '#e86c5d',
        secondary: '#00ced1',
        accent: '#e86c5d',
        neutral: {
          '50': '#f9fafb',
          '100': '#f3f4f6',
          '200': '#e5e7eb',
          '300': '#d1d5db',
          '400': '#9ca3af',
          '500': '#6b7280',
          '600': '#4b5563',
          '700': '#374151',
          '800': '#1f2937',
          '900': '#121214',
          '950': '#0a0a0b',
        },
        success: '#22c55e',
        warning: '#f59e0b',
        error: '#ef4444',
        info: '#00ced1',
        surface: {
          'background': '#0a0a0b',
          'foreground': '#ffffff',
          'card': '#1a1a1d',
          'card-foreground': '#ffffff',
          'muted': '#121214',
          'muted-foreground': '#9ca3af',
          'border': '#374151',
        },
      },
      fontFamily: {
        display: ['Rival Sans', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Menlo', 'monospace'],
      },
      fontSize: {
        'hero': ['3.5rem', { lineHeight: '1.1', fontWeight: '700' }],
        'h2': ['2.25rem', { lineHeight: '1.2', fontWeight: '700' }],
        'h3': ['1.5rem', { lineHeight: '1.3', fontWeight: '500' }],
        'body-lg': ['1.125rem', { lineHeight: '1.7', fontWeight: '400' }],
        'body': ['1rem', { lineHeight: '1.6', fontWeight: '400' }],
        'caption': ['0.875rem', { lineHeight: '1.5', fontWeight: '400' }],
        'code': ['0.875rem', { lineHeight: '1.6', fontWeight: '400' }],
      },
      spacing: {
        '1': '0.25rem',
        '2': '0.5rem',
        '3': '0.75rem',
        '4': '1rem',
        '6': '1.5rem',
        '8': '2rem',
        '12': '3rem',
        '16': '4rem',
        '24': '6rem',
      },
      borderRadius: {
        none: '0',
        'sm': '0.125rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      screens: {
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1536px',
      },
      maxWidth: {
        content: '48rem',
      },
    },
  },
};